### ISSUE TITLE
White paper maintenance

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#171]
We can discuss the plan for the maintenance of the [white paper](https://w3c.github.io/miniapp/white-paper/) here.

**Comment by lianqi** [comment]
I suggest we keep maintaining the MiniApps White Paper. 

Goal: leverage this white paper as an overview for all the MiniApps related standards work in W3C. It introduces the MiniApp industry landscape, the current standards work, the new ideas that are incubated in W3C

How: start to collect the work summary at the end of 2021, update the content, maybe revise the structure a bit, and publish it in early 2022. This white paper can be published annualy. So the next edition is MiniApps Standardization White Paper 2021. The content should not be too technical, make it easy for non-tech guys to understand, and with links to specific technical documents so that developers can have a deeper look of the technical stuff. 

Initial ideas of basic structure:
- Miniapps Oveview, inlcude core features, industry landscape
- Current standards work, the WG work
- New ideas incubated, the CG work
- MiniApps and Web, the interoperability between the MiniApps and the Web

**Comment by xfq** [comment]
What we might want to mention in the white paper:

* MiniApps usually need to be reviewed by the hosting platform to go online
* MiniApps usually have a domain name safelist, to permit scripts contained in a MiniApp to access data from a URL only when the domain name is in the safelist.

**Comment by Sharonzd** [comment]
Possible outline
1. Overview
- Overview Introduction
- Multi platform (IoT)

2. Core Features
- Login
- Sub packaging
- Dynamic libraries
- User experience: components rather than api to ensure user perception

3. Security features
- Auditing mechanism
- Webview component whitelist
- Capability authentication
- User authorization

4. WG work introduce
- packaging
- lifecycle
- manifest
- addressing
- widget req
- ...

5. CG work introduce
- IoT
- WoT
...

6. MiniApp and Web Interoperability
- PWA: more comparisons

**Comment by QingAn** [comment]
Discussed outline. We can continue discussion.

1.	Abstract
2.	Status of This Document
3.	Introduction
- Problems
- What is MiniApp?
- Can we just use PWA? -> Updated to “gap between MiniApps and PWA” @MichaelWangzitao  , @espinr 
- Case studies
-- Case 1: Shared Bicycle Service
-- Case 2: AR Zoo
-- Case 3: MiniApp for IoT -> Updated to MiniApp for Vehicle @xfq 
-- Case 4: MiniApp for IoT @QingAn 
-- Case 5: MiniApp for TV @QingAn 
4.	MiniApp Overview

- Core Features
-- Separate the View Layer from the Logic Layer
-- Rich APIs and Components
-- MiniApp Constructor
-- MiniApp Widgets
-- Single-Instance, Multi-Entries
-- Performance and User Experience
-- More to add @Sharonzd
- MiniApp Market

5.	Working with the Web

- Application Lifecycle
-- Hybrid Rendering
-- Transition Animation
-- Standardise the Package Constructor of MiniApp
-- Standardise the navigation to a MiniApp page
-- MiniApp Widgets

- Performance and Tuning
-- Define an event of time to interactive in MiniApp

- Graphics and Media
-- 3D Model Element
-- Face Tracking
-- Hand gestures tracking and recognition
-- Low level AR APIs based on ARCore and ARKit
6.	Current standards work, the WG work

- Lifecycle @QingAn 
- Manifest @espinr 
- Packaging @MichaelWangzitao
- Addressing @Sharonzd 
- Widget req @Canfeng
- Implementation, converting tool @MichaelWangzitao
7.	New ideas incubated, the CG work

- UI components @MichaelWangzitao
- MiniApp for IoT @QingAn 
- Widgets XXX @Canfeng
8.	Security and Privacy Consideration

- Add something about “MiniApps usually need to be reviewed by the hosting platform to go online”  @Sharonzd 
- Add something about “MiniApps usually have a domain name safelist, to permit scripts contained in a MiniApp to access data from a URL only when the domain name is in the safelist.”  @Sharonzd 
9.	Way Forward in W3C
10.	Glossary
11.	Gap Analysis
12.	Acknowledgments

**Comment by xfq** [comment]
New version published: https://www.w3.org/TR/mini-app-white-paper/

**Comment by xfq** [comment]
Closing.
