### ISSUE TITLE
Charter: will platform operations need to be in scope?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/miniapp#76]
I imagine that some security and privacy mitigations will be easier to make operationally than in protocol.  Would you prefer to leave operations in scope, to allow for those?  Or do you want to be constrained to making those mitigations in protocol?

**Comment by xfq** [comment]
Link to related section: https://w3c.github.io/miniapp/charters/wg-2020.html#out-of-scope

**Comment by xfq** [comment]
In yesterday's CG call we decided to remove the Out of Scope section: https://www.w3.org/2020/06/11-miniapp-minutes.html#item06

**Comment by samuelweiler** [comment]
Interesting that you removed the scope limitation rather than explicitly making operations in scope.  Do you want to make them in-scope, so we don't hit roadblocks down the way?  (I'm imagining a WG saying "we can't specify operations" - since this charter doesn't explicitly put them in-scope.). Reopening for that answer.

**Comment by lianqi** [comment]
> 
> 
> Interesting that you removed the scope limitation rather than explicitly making operations in scope. Do you want to make them in-scope, so we don't hit roadblocks down the way? (I'm imagining a WG saying "we can't specify operations" - since this charter doesn't explicitly put them in-scope.). Reopening for that answer.

Hi Sam, 
The operation of MiniApp vendors vary. The MiniApp CG originally thought that the operation, mainly the business side of how to operate MiniApp should not be in the scope of the charter, only the technical part that needs to be standardized. In the later discussion, the group thinks it is not needed to state that in the charter, since what is not in the scope is out of scope. And it would be hard to enumerate the items related to MiniApp but should not be in the scope.  So, the revised charter takes the simple way of deleting the out of scope part. I hope this anwers to your question.

**Comment by xfq** [comment]
@samuelweiler Does @lianqi's comment answers your question?

**Comment by samuelweiler** [comment]
This was more of a nudge.  As indicated in the query, leaving operations out of scope may leave you doing much harder work to address privacy and/or security issues in (exclusively) protocol.  If  the proposed WG is fine with that constraint - knowing that addressing those issues in (exclusively) protocol might require some pretty serious engineering work - then I am also.

**Comment by xfq** [comment]
Closing per https://www.w3.org/2020/11/19-miniapp-minutes.html#t04
